### ISSUE TITLE
Guide for Lambda as Activities

### ISSUE THREAD

**Issue by nitin02** [awsdocs/aws-java-developer-guide#1]
I'm currently in the process of creating a SWF with multiple Lambda functions as activities. Can you provide an example/documentation on how to achieve this. I have searched a lot for how Lambda functions can be scheduled using deciders but couldn't find any.

Basically, In my case, The input to the Workflow (from the WorkFlowStarter) determines which Lambda function to be executed first. Thereafter, the result of a Lambda function determines which Lambda function to be executed next. An example (in Java) would be helpful.

**Comment by EronHennessey** [comment]
I agree, and will add such a topic.

For now, you can look at [AWS Lambda Tasks](http://docs.aws.amazon.com/amazonswf/latest/developerguide/lambda-task.html) in the SWF developer guide. It's not language-specific, but it does show the data that you'd need to pass to [ScheduleLambdaFunctionDecisionAttributes](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/ScheduleLambdaFunctionDecisionAttributes.html) and provides other information that you'll need, such as setting up the necessary IAM role.

Here are the basics using the Java SDK:

In your workflow worker, you respond to a decision task by returning a list of [Decisions](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/Decision.html) in your [RespondDecisionTaskCompletedRequest]() object:

``` .java
ScheduleActivityTaskDecisionAttributes attrs =
            new ScheduleActivityTaskDecisionAttributes()
                .withActivityType(new ActivityType()
                .withName(HelloTypes.ACTIVITY)
                .withVersion(HelloTypes.ACTIVITY_VERSION))
                .withActivityId(UUID.randomUUID().toString())
                .withInput(workflow_input);

        decisions.add(
                new Decision()
                    .withDecisionType(DecisionType.ScheduleActivityTask)
                    .withScheduleActivityTaskDecisionAttributes(attrs));
```

If you're scheduling an Activity, the decisions specify a [DecisionType.ScheduleActivityTask](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/DecisionType.html) with the necessary data to identify the activity to run (and input data, etc.) in [ScheduleActivityTaskDecisionAttributes](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/ScheduleLambdaFunctionDecisionAttributes.html).

If you want to run a _Lambda function_ instead of an Activity, you respond with **DecisionType.ScheduleLambdaFunction**, and an associated [ScheduleLambdaFunctionDecisionAttributes](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/ScheduleLambdaFunctionDecisionAttributes.html).

The fields that are required are _name_ (the Lambda function name) and _id_ (An identifier of your choice that SWF uses to identify the task).

Note that the Lambda function must be in the same region as your workflow, and the workflow must be registered with an IAM role that gives SWF access to call Lambda functions, by using the **.withDefaultLambdaRole()** method in the [RegisterWorkflowTypeRequest](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/RegisterWorkflowTypeRequest.html).

Creating this IAM role is described in the [Lambda Tasks](http://docs.aws.amazon.com/amazonswf/latest/developerguide/lambda-task.html#d0e9536) article.

**Comment by nitin02** [comment]
Thank you for your succinct response.

Would you suggest registering these Lambda functions as individual Activities (The Lambda function will be called inside the Activity wrapper as a registered **ActivityType**) or would you suggest scheduling them directly from the decider (**WorkFlowWorker**). Is there any specific advantage?

Currently, I'm under the impression that calling a **Lambda** function inside a **ActivityType** would be better in a logging perspective i.e I'd know which Lambda function failed from the Activity log rather than the event log. 
Also, there might be a way to know to monitor the progress of a workflow execution by understanding what Activity is being presently executed.

**Comment by EronHennessey** [comment]
While you _can_ do this (call Lambda from inside an activity), the SWF API is designed around using Lambda functions as top-level tasks, just like classic SWF activities are. Lambda tasks report on your workflow event history, and you also get standard Lambda function history + run transcripts reported by CloudWatch.

Within a Lambda task, you can log information simply by using System.out/System.err.println(). There's a lot more information about this in the [Java Programming Model](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model.html) section in the Lambda Guide.

**Comment by EronHennessey** [comment]
_Update_: The new Amazon SWF [Lambda tasks](http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/swf-lambda-task.html) topic has been added. Closing this issue!
